version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: monthly
    time: "21:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: wasm-bindgen-test
    versions:
    - 0.3.20
