image:
  file: .gitpod.Dockerfile

tasks:
  - init: time cargo build
    command: cargo test
  - init: cargo install cargo-insta cargo-workspaces && exit # cargo insta test && cargo insta accept to update snapshots
  - init: yarn && cd wasm && wasm-pack build --release --scope=gengjiawen && cd ./pkg && yarn link && cd ../../ast-website/website && yarn && yarn link @gengjiawen/monkey-wasm # astexplorer

vscode:
  extensions:
    - gengjiawen.vscode-wakatime-gitpods
    - vadimcn.vscode-lldb
    - gengjiawen.vscode-npm-dependency
    - gengjiawen.npm-dependency-links
    - gengjiawen.vscode-wasm
    - gengjiawen.vscode-postfix-ts
