image:
  file: .gitpod.Dockerfile

tasks:
  - init: cargo build
    command: cargo test
  - init: cargo install cargo-insta # cargo insta test && cargo insta accept to update snapshots
  - init: cd wasm && wasm-pack build && cd ../ast-website/ && yarn # astexplorer
  - init: fish