packages:
  - packages/*
  - wasm/pkg

allowBuilds:
  '@swc/core': true
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
  sharp: true

minimumReleaseAgeExclude:
  - '@gengjiawen/monkey-wasm@0.12.1'
  - ovsx@1.0.1

onlyBuiltDependencies:
  - '@swc/core'
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
  - sharp
