version: 2.1

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: gengjiawen/node-build
    steps:
      - checkout
      - run: npx envinfo
      - run:
          name: test
          command: |
            cd wasm && wasm-pack build --scope=gengjiawen
      - store_artifacts:
          path: wasm/pkg

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
