import { StringStream } from '@codemirror/language'
import { describe, expect, it } from 'vitest'

import { arm64TokenDoc } from '../arm64Docs'
import { arm64StreamParser } from '../arm64Language'

interface Classified {
  text: string
  style: string | null
}

function tokenize(line: string): Classified[] {
  const stream = new StringStream(line, 4, 2)
  const out: Classified[] = []
  while (!stream.eol()) {
    stream.start = stream.pos
    const style = arm64StreamParser.token(stream, {})
    if (stream.pos === stream.start) {
      throw new Error(`tokenizer failed to advance at ${stream.pos} in ${line}`)
    }
    out.push({ text: stream.current(), style })
  }
  return out
}

/** Non-null classifications only — whitespace and punctuation drop out. */
function styled(line: string): Classified[] {
  return tokenize(line).filter((token) => token.style !== null)
}

// Real lines from asm/snapshots, covering every emitter shape.
describe('arm64StreamParser', () => {
  it('classifies the generated-file header as a comment', () => {
    expect(styled('// Generated by monkey-asm. Do not edit.')).toEqual([
      { text: '// Generated by monkey-asm. Do not edit.', style: 'comment' },
    ])
  })

  it('classifies directives and their symbol arguments', () => {
    expect(styled('    .globl main')).toEqual([
      { text: '.globl', style: 'directive' },
      { text: 'main', style: 'label' },
    ])
    expect(styled('    .section .rodata')).toEqual([
      { text: '.section', style: 'directive' },
      { text: '.rodata', style: 'directive' },
    ])
    expect(styled('    .byte 0x68, 0x65')).toEqual([
      { text: '.byte', style: 'directive' },
      { text: '0x68', style: 'number' },
      { text: '0x65', style: 'number' },
    ])
  })

  it('classifies the prologue push', () => {
    expect(styled('    stp x29, x30, [sp, #-16]!')).toEqual([
      { text: 'stp', style: 'mnemonic' },
      { text: 'x29', style: 'register' },
      { text: 'x30', style: 'register' },
      { text: 'sp', style: 'register' },
      { text: '#-16', style: 'number' },
    ])
  })

  it('classifies adrp plus :lo12: address materialization', () => {
    expect(styled('    adrp x0, g_globals')).toEqual([
      { text: 'adrp', style: 'mnemonic' },
      { text: 'x0', style: 'register' },
      { text: 'g_globals', style: 'label' },
    ])
    expect(styled('    add x0, x0, :lo12:g_globals')).toEqual([
      { text: 'add', style: 'mnemonic' },
      { text: 'x0', style: 'register' },
      { text: 'x0', style: 'register' },
      { text: ':lo12:', style: 'reloc' },
      { text: 'g_globals', style: 'label' },
    ])
  })

  it('classifies shifted constants', () => {
    expect(styled('    movz x1, #0x1, lsl #16')).toEqual([
      { text: 'movz', style: 'mnemonic' },
      { text: 'x1', style: 'register' },
      { text: '#0x1', style: 'number' },
      { text: 'lsl', style: 'shift' },
      { text: '#16', style: 'number' },
    ])
  })

  it('classifies runtime calls with trailing comments', () => {
    expect(styled('    bl rt_mul                       // 2 * 3')).toEqual([
      { text: 'bl', style: 'mnemonic' },
      { text: 'rt_mul', style: 'runtime' },
      { text: '// 2 * 3', style: 'comment' },
    ])
  })

  it('classifies branches to local labels', () => {
    expect(styled('    tbnz x8, #0, .L0')).toEqual([
      { text: 'tbnz', style: 'mnemonic' },
      { text: 'x8', style: 'register' },
      { text: '#0', style: 'number' },
      { text: '.L0', style: 'label' },
    ])
    expect(styled('.Lfn0:                              // fn add(a, b)')).toEqual([
      { text: '.Lfn0', style: 'label' },
      { text: '// fn add(a, b)', style: 'comment' },
    ])
  })

  it('classifies frame loads with negative offsets', () => {
    expect(styled('    ldur x1, [x29, #-32]            // a')).toEqual([
      { text: 'ldur', style: 'mnemonic' },
      { text: 'x1', style: 'register' },
      { text: 'x29', style: 'register' },
      { text: '#-32', style: 'number' },
      { text: '// a', style: 'comment' },
    ])
  })

  it('leaves unknown words unstyled instead of guessing', () => {
    expect(styled('    unknown_word 5')).toEqual([
      { text: '5', style: 'number' },
    ])
  })

  it('maps every style it produces through the token table', () => {
    const lines = [
      '    stp x29, x30, [sp, #-16]!',
      '    add x0, x0, :lo12:g_globals',
      '    movz x1, #0x1, lsl #16',
      '    bl rt_mul // slow path',
      '    .globl main',
      '.L0:',
    ]
    const table = arm64StreamParser.tokenTable ?? {}
    for (const line of lines) {
      for (const { text, style } of styled(line)) {
        expect(table, `${style} (from ${text})`).toHaveProperty(style ?? '')
      }
    }
  })

  it('documents every token it highlights as meaningful', () => {
    const documented = new Set([
      'mnemonic',
      'register',
      'runtime',
      'label',
      'directive',
      'shift',
    ])
    const pane = [
      '    .text',
      '    .globl main',
      'main:',
      '    stp x29, x30, [sp, #-16]!',
      '    mov x29, sp',
      '    adrp x0, g_globals',
      '    add x0, x0, :lo12:g_globals',
      '    movz x1, #0                     // global slot count',
      '    bl rt_globals_init',
      '    str x0, [sp, #-16]!             // left operand',
      '    ldr x0, [sp], #16               // left operand',
      '    orr x8, x0, x1                  // SMI check on both bit0',
      '    tbnz x8, #0, .L0',
      '    adds x8, x0, x1',
      '    bvs .L0',
      '    b .L1',
      '.Lmain_exit:',
      '    mov w0, #0                      // exit code',
      '    ldp x29, x30, [sp], #16',
      '    ret',
      '    .bss',
      '    .balign 8',
      'g_globals:                          // 0 global slot(s)',
      '    .skip 0',
    ]
    for (const line of pane) {
      for (const { text, style } of styled(line)) {
        if (style !== null && documented.has(style)) {
          expect(arm64TokenDoc(text), `${text} on ${line}`).not.toBeNull()
        }
      }
    }
  })
})
