name: prepare-dist
on:
  push:
    branches:
      - 'release-**'
      - release-v0.9.1
jobs:
  prepare-dist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: docker run -v $PWD:/pwd -w /pwd gengjiawen/node-build bash -c "yarn && pnpx ts-node scripts/bump_cargo_packages.ts"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: prepare rust packages'
