name: prepare-dist
on:
  push:
    branches:
      - release-*
jobs:
  prepare-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo install cargo-workspaces
      - run: yarn && npx ts-node scripts/bump_cargo_packages.ts