name: prepare-dist
on:
  push:
    branches:
      - release-*
jobs:
  prepare-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # npx not work in this cases due to some werid permission issues
      - run: docker run -v $PWD:/pwd -w /pwd gengjiawen/node-build bash -c "yarn && node node_modules/.bin/ts-node scripts/bump_cargo_packages.ts"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: prepare rust packages"
